[workspace]
allow_dirty = true
dependencies_update = false
semver_check = false

[[package]]
name = "euromail"
git_tag_name = "sdk/rust/v{{ version }}"
git_release_name = "Rust SDK v{{ version }}"
git_release_enable = true
git_tag_enable = true
changelog_path = "CHANGELOG.md"
